### ISSUE TITLE
mmap: use copy-on-write mapping when MAP_PRIVATE is passed to mmap()

### ISSUE THREAD

**Issue by komh** [komh/os2compat#5]

**Comment by komh** [comment]
Currently, always read a file into a memory even if a read only mode. Memory waste. 

However, is this possible on application level ?

**Comment by dryeo** [comment]
On 10/06/16 05:06 PM, KO Myung-Hun wrote:

> Currently, always read a file into a memory even if a read only mode.
> Memory waste.
> 
> However, is this possible on application level ?

Using DosAliasMem so the kernel is aware and can do its copy on write 
thing was mentioned as one solution on the Os2-dev list, though whether 
fine grained enough is questionable.

**Comment by komh** [comment]
Good idea. 

Maybe it would be possible if applying technic used for MAP_SHARED and using exception handlers in which reallocating a memory and copying contents.

There are too many things to do this, but it seems not to be impossible.

Thanks.

**Comment by komh** [comment]
I've implemented copy-on-write feature separately. See
- https://github.com/komh/os2codes/blob/master/memory/copyonwrite.c
- https://github.com/komh/os2codes/blob/master/memory/copyonwrite.h
- https://github.com/komh/os2codes/blob/master/memory/copyonwrite-test.c

It's possible to implmenet copy-on-write. However, I doubt that it's meaningful. If it has meaning, it's that implementation of copy-on-write is not impossible. It's neither more nor less than 'not impossible'.

As a result, it has no sense to implement this issue.
